### ISSUE TITLE
Istarissues project is private

### ISSUE THREAD

**Issue by absin1** [ISTARSkills/CMS#2]
While filing new issues on Istarissues, I get a 404. I wonder how the content team will be able to add issues, and how Teju did it yesterday.

Links giving 404:
https://github.com/ISTARSkills/istarissues
https://github.com/ISTARSkills/istarissues/issues/new

**Comment by suryatejamv** [comment]
Resolution suggested by Vaibhav Sir. Users need to create GitHub account and request for access for creating issues for the first time.
