### ISSUE TITLE
Course list not updated in Course Structure

### ISSUE THREAD

**Issue by absin1** [ISTARSkills/CMS#3]
During testing, I added a course named "TestingCMS" CourseID "40". The course appears in[ Modify Course Details page](http://beta.talentify.in:8080/content/content_admin/course_list.jsp), but not in [course structure page](http://beta.talentify.in:8080/content/content_admin/course_structure.jsp)!

**Comment by suryatejamv** [comment]
The issue is fixed. Please check now: http://beta.talentify.in:8080/content/content_admin/course_structure.jsp
